DB.Enum = T{}

DB.Enum.Mode = T{
    INC = "inc",
	SET = "set",
}

DB.Enum.Trackable = T{
    TOTAL               = "Total",
    TOTAL_NO_SC         = "No SC Total",
    MELEE               = "Melee",               -- Melee
    MELEE_MAIN          = "Melee Mainhand",
    MELEE_OFFHAND       = "Melee Offhand",
    MELEE_KICK          = "Melee Kicks",
    PET_MELEE           = "Pet Melee",
    PET_MELEE_DISCRETE  = "Pet Melee Discrete",
    MELEE_COUNTERED     = "Countered",
    RANGED              = "Ranged",              -- Ranged
    RANGED_SQUARE       = "Ranged Square Hit",
    RANGED_TRUE         = "Ranged True Strike",
    PET_RANGED          = "Pet Ranged",
    THROWING            = "Throwing",
    WS                  = "Weaponskills",        -- TP Action
    PET_WS              = "Pet Weaponskills",
    SC                  = "Skillchains",
    ABILITY             = "Abilities",           -- Ability
    ABILITY_DAMAGING    = "Damaging Abilities",
    ABILITY_HEALING     = "Healing Abilities",
    ABILITY_MP_RECOVERY = "MP Recovery Abilities",
    ABILITY_GENERAL     = "General Ability",
    MANEUVER            = "Maneuver",
    PHANTOM_ROLL        = "Corsair Roll",
    PET                 = "Pet",                 -- Pets
    PET_ABILITY         = "Pet Ability",
    PET_HEAL            = "Pet Healing",
    PET_NUKE            = "Pet Nuking",
    PET_ENFEEBLING      = "Pet Enfeebling",
    PET_MP_DRAIN        = "Pet MP Drain",
    PET_MAGIC           = "Pet Magic",
    MAGIC               = "Spells",              -- Magic
    ENSPELL             = "Enspell",
    ENDAMAGE            = "Melee Endamage",
    ENDAMAGE_R          = "Ranged Endamage",
    ENDRAIN             = "Melee Endrain",
    ENDRAIN_R           = "Ranged Endrain",
    ENASPIR             = "Melee Enaspir",
    ENASPIR_R           = "Ranged Enaspir",
    ENDEBUFF            = "Melee Debuff",
    ENDEBUFF_R          = "Ranged Debuff",
    NUKE                = "Nuking",
    HEALING             = "Healing",
    ALL_HEAL            = "Combined Healing",
    ENFEEBLE            = "Enfeebling",
    BUFF_SONG           = "BRD Buff Song",
    DEBUFF_REMOVAL      = "Debuff Removal",
    BUFF_SPELL          = "Buff Spell",
    MP_DRAIN            = "MP Drain",
    OUTGOING_SPIKE_DMG  = "Outgoing Spike Damage",
    HEALING_RECEIVED    = "Healing Received",
    DAMAGE_TAKEN_TOTAL  = "Total Damage Taken", -- Defense
    DMG_TAKEN_TOTAL_PET = "Total Pet Damage Taken",
    MELEE_DMG_TAKEN     = "Melee Damage Taken",
    MELEE_PET_DMG_TAKEN = "Melee Pet Damage Taken",
    DEF_EVASION         = "Evasion",
    DEF_PARRY           = "Parry",
    DEF_SHADOWS         = "Shadow Absorption",
    DEF_COUNTER         = "Counter",
    DEF_GUARD           = "Guard",
    DEF_BLOCK           = "Shield Block",
    DEF_CRIT            = "Crits Taken",
    DEF_UNMITIGATED     = "Unmitigated Melee Damage Taken",
    INCOMING_SPIKE_DMG  = "Incoming Spike Damage",
    SPELL_DMG_TAKEN     = "Spell Damage Taken",
    SPELL_PET_DMG_TAKEN = "Spell Pet Damage Taken",
    DEF_NO_DMG_SPELLS   = "No Damage Spells",
    DEF_MP_DRAIN        = "Player MP Drained",
    DEF_ENFEEBLE        = "Player Enfeebled",
    -- SPELL_ENF_RESIST   = "Enfeeble Resist"
    TP_DMG_TAKEN        = "TP Move Damage Taken",
    PET_TP_DMG_TAKEN    = "Pet TP Move Damage Taken",
    DEATH               = "Death",               -- Misc
    DEFAULT             = "Default",
}

DB.Enum.Metric = T{
    TOTAL         = "Total",
    COUNT         = "Attempts",
    AOE_COUNT     = "AOE Targets Hit",
    CYCLE         = "Melee Cycles",          -- How many times a melee cycle occurred.
    ROUNDS        = "Attack Rounds",         -- Used in multi-attacks
    MULTI_TOTAL   = "Multi-Attack",
    MULT_ATK_1    = "Single",
    MULT_ATK_2    = "Double",
    MULT_ATK_3    = "Triple",
    MULT_ATK_4    = "Quad",
    MULT_ATK_5    = "Mult. V",
    MULT_ATK_6    = "Mult. VI",
    MULT_ATK_7    = "Mult. VII",
    MULT_ATK_8    = "Mult. VIII",
    GUARD         = "Guard",
    HIT_COUNT     = "Hits",
    SHOT_DISTANCE = "Shot Distance",
    CRIT_COUNT    = "Crit Count",
    CRIT_DAMAGE   = "Crit Damage",
    SHADOWS       = "Shadow Absorption",
    MOB_HEAL      = "Mob Heal",
    MIN           = "Min",
    MAX           = "Max",
    BURST_COUNT   = "Burst Count",
    BURST_DAMAGE  = "Burst Damage",
    OVERCURE      = "Overcure",
    MP_SPENT      = "MP Spent",
    TP_SPENT      = "TP Spent",
    SC_OPENED     = "Skillchains Opened",
    SC_CLOSED     = "Skillchains Closed",
    OVERLOAD      = "Maneuver Overload",
    PHANTOM_ROLL_FIRST_ROLL = "Phantom Roll First Rolls",
    PHANTOM_ROLL_REROLL     = "Phantom Roll Rerolls",
    BUST_COUNT    = "COR Roll Bust Count",
    LUCKY_COUNT   = "COR Roll Lucky Count",
    UNLUCKY_COUNT = "COR Roll Unlucky Count",
    LUCKY_11_COUNT = "COR Roll Lucky 11 Count",
}

DB.Enum.Pet_Single_Trackable = T{
	PET_WS         = DB.Enum.Trackable.PET_WS,
	PET_ABILITY    = DB.Enum.Trackable.PET_ABILITY,
	PET_HEAL       = DB.Enum.Trackable.PET_HEAL,
	PET_NUKE       = DB.Enum.Trackable.PET_NUKE,
	PET_ENFEEBLING = DB.Enum.Trackable.PET_ENFEEBLING,
	PET_MP_DRAIN   = DB.Enum.Trackable.PET_MP_DRAIN,
	PET_MAGIC      = DB.Enum.Trackable.PET_MAGIC,
}

DB.Enum.Values = T{
    CATALOG     = "catalog",
	PET_CATALOG = "pet_catalog",
    DEBUG       = "Debug",
    IGNORE      = 'ignore',
	COMBINED    = 'combined',
    MAX_DAMAGE  = 100000,
}

DB.Enum.HEALING = T{
    ["Cure"]       = 50,	-- 35
    ["Cure II"]    = 150, 	-- 102
    ["Cure III"]   = 250, 	-- 212
    ["Cure IV"]    = 500,	-- 430
    ["Cure V"]     = 1300,
    ["Cure VI"]    = 1500,
    ["Curaga"]     = 150,	-- 102
    ["Curaga II"]  = 300,	-- 213
    ["Curaga III"] = 400,
    ["Curaga IV"]  = 500,
    ["Curaga V"]   = 800,
}

DB.Healing_Max = T{
    ["Cure"]       = 50,
    ["Cure II"]    = 150,
    ["Cure III"]   = 250,
    ["Cure IV"]    = 500,
    ["Cure V"]     = 1300,
    ["Cure VI"]    = 1500,
    ["Curaga"]     = 150,
    ["Curaga II"]  = 300,
    ["Curaga III"] = 400,
    ["Curaga IV"]  = 500,
    ["Curaga V"]   = 800,
}