DB.Enum = {
    ALL_MOBS    = "!All Mobs",
    BLANK       = "",
    CATALOG     = "catalog",
    COMBINED    = "combined",
    DEBUG       = "Debug",
    IGNORE      = "ignore",
	PET_CATALOG = "pet_catalog",
    MAX_DAMAGE  = 100000,
}

DB.Trackable = {
    TOTAL_DAMAGE               = "Total Damage",
    TOTAL_DAMAGE_NO_SKILLCHAIN = "Total Damage No Skillchain",
    ALL_HEAL                   = "All Sources Healing",
    MELEE_OVERALL              = "Melee",
    MELEE_MAIN_HAND            = "Melee Main-hand",
    MELEE_OFF_HAND             = "Melee Off-hand",
    MELEE_KICK_ATTACKS         = "Melee Kick Attacks",
    MELEE_ENSPELL              = "Melee Enspell",
    MELEE_ENDAMAGE             = "Melee Endamage",
    MELEE_ENDRAIN              = "Melee Endrain",
    MELEE_ENASPIR              = "Melee Enaspir",
    MELEE_ENDEBUFF             = "Melee Endebuff",
    MELEE_COUNTER              = "Melee Player Counters",       -- This is the player doing damage with a counter.
    RANGED_OVERALL             = "Ranged",
    RANGED_SQUARE_HIT          = "Ranged Square Hit",
    RANGED_TRUE_STRIKE         = "Ranged True Strike",
    RANGED_THROWING            = "Ranged Throwing",
    RANGED_ENDAMAGE            = "Ranged Endamage",
    RANGED_ENDRAIN             = "Ranged Endrain",
    RANGED_ENASPIR             = "Ranged Enaspir",
    RANGED_ENDEBUFF            = "Ranged Endebuff",
    WEAPONSKILL                = "Weaponskill",
    SKILLCHAIN                 = "Skillchain",
    SPELLS_OVERALL             = "Spells Overall",
    SPELLS_NUKING              = "Spells Nuking",
    SPELLS_HEALING             = "Spells Healing",
    SPELLS_DEBUFF_REMOVAL      = "Spells Debuff Removal",
    SPELLS_ENFEEBLING          = "Spells Enfeebling",
    SPELLS_BUFFS               = "Spells Buffs",
    SPELLS_BUFF_SONG           = "Spells Buff Songs",
    SPELLS_MP_DRAIN            = "Spells MP Drain",
    SPELLS_SPIKE_DAMAGE        = "Spells Spike Damage",
    PET_OVERALL                = "Pet Overall",
    PET_MELEE_OVERALL          = "Pet Melee",
    PET_MELEE_DISCRETE         = "Pet Melee Discrete",          -- This fills the role of main-hand/off-hand.
    PET_RANGED_OVERALL         = "Pet Ranged Overall",
    PET_TP                     = "Pet TP Move",
    PET_NUKING                 = "Pet Nuking",
    PET_HEALING                = "Pet Healing",
    PET_ENFEEBLING             = "Pet Enfeebling",
    PET_MP_DRAIN               = "Pet MP Drain",
    PET_GENERAL_MAGIC          = "Pet General Magic",
    ABILITY_OVERALL            = "Ability Overall",
    ABILITY_DAMAGING           = "Ability Damaging",
    ABILITY_HEALING            = "Ability Healing",
    ABILITY_MP_RECOVERY        = "Ability MP Recovery",
    ABILITY_GENERAL            = "Ability General",
    MANEUVER                   = "PUP Maneuver",
    PHANTOM_ROLL               = "COR Phantom Roll",
    DEF_DAMAGE_TAKEN_TOTAL     = "Defense Damage Taken Total",
    DEF_DAMAGE_TAKEN_TOTAL_PET = "Defense Damage Taken Total Pet",
    DEF_TP_MOVE                = "Defense TP Move",
    DEF_TP_MOVE_PET            = "Defense TP Move Pet",
    DEF_MELEE                  = "Defense Melee",
    DEF_MELEE_PET              = "Defense Melee Pet",
    DEF_EVASION                = "Defense Evasion",
    DEF_PARRY                  = "Defense Parry",
    DEF_SHADOWS                = "Defense Shadows",
    DEF_THIRD_EYE_ANTICIPATION = "Defense Third Eye Anticipation",
    DEF_COUNTERED              = "Defense Player Countered",    -- This is the player being countered during an offensive melee attack.
    DEF_GUARD                  = "Defense Guard",
    DEF_SHIELD_BLOCK           = "Defense Shield Block",
    DEF_UNMITIGATED            = "Defense Unmitigated",
    DEF_NUKING                 = "Defense Nuking",
    DEF_NUKING_PET             = "Defense Nuking Pet",
    DEF_ENFEEBLING             = "Defense Enfeebling",
    DEF_MP_DRAIN               = "Defense MP Drain",
    DEF_SPIKES                 = "Defense Spikes",
    DEF_HEALING_RECEIVED       = "Defense Healing Received",    -- Self healing is ignored.
    DEATH                      = "Death",
    DEF_NO_DAMAGE_SPELLS       = "Defense No Damage Spells",    -- Unsure of the purpose for this.
    DEF_CRITICAL               = "Defense Critical Hit",        -- This might not be necessary with DEF_MELEE
    DEFAULT                    = "Unknown Melee Type",
}

DB.Metric = {
    TOTAL              = "Total",
    ATTEMPTS           = "Attempts",
    AOE_ATTEMPTS       = "AOE Attempts",            -- Used primarily for AOE debuff tracking.
    HIT_COUNT          = "Hits",
    MIN                = "Minimum",
    MAX                = "Maximum",
    CRITICAL_COUNT     = "Critical Hit Count",      -- These need to be metrics so that each discrete trackable can have
    CRITICAL_DAMAGE    = "Critical Hit Damage",     -- critical hit data.
    CRITICAL_MIN       = "Critical Hit Minimum",
    CRITICAL_MAX       = "Critical Hit Maximum",
    MELEE_ROUNDS       = "Melee Attack Rounds",     -- How many times a group of melee attacks occurred.
    MELEE_STRIKES      = "Melee Attack Strikes",    -- Used in multi-attacks. Can probably replace with ATTEMPTS.
    MULTI_ATTACK_TOTAL = "Multi Attack Total",
    MULTI_ATTACK_1     = "Melee Single Attack",
    MULTI_ATTACK_2     = "Melee Double Attack",
    MULTI_ATTACK_3     = "Melee Triple Attack",
    MULTI_ATTACK_4     = "Melee Quad Attack",
    MULTI_ATTACK_5     = "Melee Penta Attack",
    MULTI_ATTACK_6     = "Melee Multi Attack VI",
    MULTI_ATTACK_7     = "Melee Multi Attack VII",
    MULTI_ATTACK_8     = "Melee Multi Attack VIII",
    SHADOW_ABSORPTION  = "Shadow Absorption",
    MOB_HEALING        = "Mob Healing",
    SHOT_DISTANCE      = "Shot Distance",
    TP_SPENT           = "TP Spent",
    SKILLCHAIN_OPENED  = "Skillchains Opened",
    SKILLCHAIN_CLOSED  = "Skillchains Closed",
    MAGIC_BURST_COUNT  = "Magic Burst Count",
    MAGIC_BURST_DAMAGE = "Magic Burst Damage",
    OVERCURE           = "Overcure",
    MP_SPENT           = "MP Spent",
    OVERLOAD           = "Maneuver Overload",
    FIRST_ROLL         = "COR Roll First Rolls",
    REROLL             = "COR Roll Rerolls",
    BUSTS              = "COR Roll Bust Count",
    LUCKY              = "COR Roll Lucky Count",
    LUCKY_11           = "COR Roll Lucky 11 Count",
    UNLUCKY            = "COR Roll Unlucky Count",
    GUARD              = "Guard",                -- Delete this?
}

DB.Update_Mode = {
    INC = "inc",
    SET = "set",
}

-- Used in lists to find all the actions that pets have done.
DB.Pet_Single_Trackable = {
	PET_WS         = DB.Trackable.PET_TP,
	PET_HEAL       = DB.Trackable.PET_HEALING,
	PET_NUKE       = DB.Trackable.PET_NUKING,
	PET_ENFEEBLING = DB.Trackable.PET_ENFEEBLING,
	PET_MP_DRAIN   = DB.Trackable.PET_MP_DRAIN,
	PET_MAGIC      = DB.Trackable.PET_GENERAL_MAGIC,
}

DB.Healing_Max_Defaults = {
    ["Cure"]       = 50,	-- 35
    ["Cure II"]    = 150, 	-- 102
    ["Cure III"]   = 250, 	-- 212
    ["Cure IV"]    = 500,	-- 430
    ["Cure V"]     = 1300,
    ["Cure VI"]    = 1500,
    ["Curaga"]     = 150,	-- 102
    ["Curaga II"]  = 300,	-- 213
    ["Curaga III"] = 400,
    ["Curaga IV"]  = 500,
    ["Curaga V"]   = 800,
}

-- This is the configurable healing max used for overcure.
DB.Healing_Max = {
    ["Cure"]       = 50,
    ["Cure II"]    = 150,
    ["Cure III"]   = 250,
    ["Cure IV"]    = 500,
    ["Cure V"]     = 1300,
    ["Cure VI"]    = 1500,
    ["Curaga"]     = 150,
    ["Curaga II"]  = 300,
    ["Curaga III"] = 400,
    ["Curaga IV"]  = 500,
    ["Curaga V"]   = 800,
}